name: Build docker image for latest release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get project versions
        run: |
          echo "server_version=$(cat package.json | jq ".version" | tr -d '"\r\n')" >> $GITHUB_OUTPUT
          echo "client_version=$(cat faucet-client/package.json | jq ".version" | tr -d '"\r\n')" >> $GITHUB_OUTPUT
      - name: Build and push multi-arch images
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file Dockerfile \
            --tag pk910/powfaucet:v${{ env.server_version }} \
            --tag pk910/powfaucet:v2-stable \
            --push .
